version: '3.4'

services:
  php:
    image: ${CI_REGISTRY_IMAGE}/php:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: bash -c "${REPLACE_OWNER} && /opt/php-fpm.sh"
    volumes:
      - ${PWD}/src/:/var/www/html/
    env_file:
      - ./.env
  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: /opt/nginx.sh
    ports:
      - 127.0.132.1:${FREE_PORT}:80
    volumes:
      - ${PWD}/src/:/var/www/html/
  mysql:
    image: ${CI_REGISTRY_IMAGE}/mysql:${CI_COMMIT_REF_SLUG}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DB}
  redis:
    image: ${CI_REGISTRY_IMAGE}/redis:${CI_COMMIT_REF_SLUG}
  pma:
    image: phpmyadmin/phpmyadmin:latest
    restart: ${RESTART}
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASS}
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - mysql
    ports:
      - 127.0.132.2:${FREE_PORT}:80
  rc:
    image: rediscommander/redis-commander
    restart: ${RESTART}
    environment:
      - REDIS_HOSTS=local:${REDIS_HOST}:${REDIS_PORT}
    ports:
      - 127.0.132.3:${FREE_PORT}:8081
