image:
  name: docker/compose:1.23.1
  entrypoint: [""]

before_script:
  - apk add --no-cache make bash curl git
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make build
    - make push
  only:
    - dev
    - test
  tags:
    - any_docker

deploy:
  stage: deploy
  script:
    - make deploy
  only:
    - dev
    - test
  tags:
    - server_docker
  when:
    manual