version: '3.4'

services:
  traefik:
    image: traefik
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    env_file:
      - ./.env
      - ./local/.env
    volumes:
      - ../../app/public/:/var/www/html/public/
    labels:
      - "traefik.enable=true"
  php:
    env_file:
      - ./.env
      - ./local/.env
    entrypoint:
      - /bin/bash
      - -c
      - "groupmod --non-unique --gid ${CURRENT_GID} www-data && usermod --non-unique --uid ${CURRENT_UID} www-data && /opt/wait-for-it.sh ${MYSQL_HOST}:${MYSQL_PORT} -- /opt/php-fpm.sh"
    volumes:
      - ../../app/:/var/www/html/
  composer:
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    image: ${CI_REGISTRY_IMAGE}/final/php:${CI_COMMIT_REF_SLUG}
    env_file:
      - ./.env
      - ./local/.env
    entrypoint:
      - /bin/bash
      - -c
      - 'groupmod --non-unique --gid ${CURRENT_GID} www-data && usermod --non-unique --uid ${CURRENT_UID} www-data && sudo -EH -u www-data bash -c "composer install --prefer-dist --ignore-platform-reqs"'
    volumes:
      - ../../app/:/var/www/html/
  pma:
    container_name: ${COMPOSE_PROJECT_NAME}_pma
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_USER=${MYSQL_USERNAME}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
  redis-commander:
    container_name: ${COMPOSE_PROJECT_NAME}_rc
    restart: always
    image: rediscommander/redis-commander
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:${REDIS_HOST}:${REDIS_PORT}
    labels:
      - "traefik.enable=true"