version: '3.4'

services:
  php:
    image: ${CI_REGISTRY_IMAGE}/php:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: /opt/php-fpm.sh
  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: /opt/nginx.sh
  redis:
    image: ${CI_REGISTRY_IMAGE}/redis:${CI_COMMIT_REF_SLUG}
  mysql:
    image: ${CI_REGISTRY_IMAGE}/mysql:${CI_COMMIT_REF_SLUG}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DB}
  listener1:
    image: ${CI_REGISTRY_IMAGE}/php:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: /opt/listener.sh
  listener2:
    image: ${CI_REGISTRY_IMAGE}/php:${CI_COMMIT_REF_SLUG}
    restart: ${RESTART}
    command: /opt/listener.sh