version: '3.4'

services:
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    image: ${CI_REGISTRY_IMAGE}/final/mysql:${CI_COMMIT_REF_SLUG}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    volumes:
      - /var/lib/mysql_${COMPOSE_PROJECT_NAME}/:/var/lib/mysql/
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    image: ${CI_REGISTRY_IMAGE}/final/redis:${CI_COMMIT_REF_SLUG}
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    restart: always
    image: ${CI_REGISTRY_IMAGE}/final/php:${CI_COMMIT_REF_SLUG}
    command: "/opt/wait-for-it.sh ${MYSQL_HOST}:${MYSQL_PORT} -- /opt/php-fpm.sh"
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    image: ${CI_REGISTRY_IMAGE}/final/nginx:${CI_COMMIT_REF_SLUG}